"""update_asset_model adding sector and coupon_rate column along constraints

Revision ID: 1970c23e9712
Revises: e6f0f83909e1
Create Date: 2026-08-30 12:06:01.855235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1970c23e9712'
down_revision: Union[str, Sequence[str], None] = 'e6f0f83909e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('coupon_rate', sa.String(), nullable=True))
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_check_constraint(batch_op.f('ck_assets_check_asset_has_couponRate'), "NOT ( asset_type == 'AssetType.BOND' AND coupon_rate IS NULL)")
        batch_op.create_check_constraint(batch_op.f('ck_assets_check_asset_has_sector'), "NOT ( asset_type == 'AssetType.STOCK' AND sector IS NULL)")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_assets_check_asset_has_sector'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_assets_check_asset_has_couponRate'), type_='check')
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('coupon_rate')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
