"""typed columns, explicit Numeric precision

Revision ID: a058a6d80a1b
Revises: da138dd2a2d9
Create Date: 2026-10-01 23:55:53.612796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a058a6d80a1b'
down_revision: Union[str, Sequence[str], None] = 'da138dd2a2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
