"""add_unique_constraint_holding_account_symbol

Revision ID: da138dd2a2d9
Revises: 1970c23e9712
Create Date: 2026-09-29 19:42:09.737137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da138dd2a2d9'
down_revision: Union[str, Sequence[str], None] = '1970c23e9712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Remove duplicate holdings — keep the row with the highest quantity
    # for each (account_id, symbol) pair, delete the rest.
    op.execute("""
        DELETE FROM holdings
        WHERE id NOT IN (
            SELECT DISTINCT ON (account_id, symbol) id
            FROM holdings
            ORDER BY account_id, symbol, quantity DESC
        )
    """)

    # Step 2: Now it's safe to add the unique constraint
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_holding_account_symbol', ['account_id', 'symbol'])



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_holding_account_symbol', type_='unique')

    # ### end Alembic commands ###
